### ISSUE TITLE
Configure custom domain name suggests wrong FLOWERPOT_ROOT_URL

### ISSUE THREAD

**Issue by c6c7** [wikiavec/flowerpot#1]
Thank you for writing Hyperdraft! I'm very excited to try it out.

When I forked flowerpot to configure index.php for use with my custom domain, I tried to use the FLOWERPOT_ROOT_URL provided by "Configure custom domain name" in Hyperdraft and it failed. I realized that it seems to have wrongly appended 'index.html' on the end of the url.

(Shameless plug: I'm using Vercel and forked your project to provide a configuration for Vercel instead of Apache. The configuration was almost as simple as the .htaccess. You can see my fork at https://github.com/chckyn/flowerpot.)

**Comment by c6c7** [comment]
It just occurred to me that I'm actually reporting a bug in Hyperdraft and not flowerpot. I have filed feedback there. Please feel free to close this issue if this is not the right place to track the problem.

**Comment by rosano** [comment]
I corrected some of the logic, can you try again? What does 'failed' mean?

**Comment by c6c7** [comment]
By "failed", I meant that it provided a link a form that was not compatible with flowerpot since index.html is appended to the end.
